# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

POTATOES = [
  {:title => '300', :director => 'Zack Snyder', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '9-Mar-2007'},
  {:title => '50/50', :director => 'Jonathan Levine', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '30-Sep-2011'},
  {:title => '500 Days of Summer', :director => 'Marc Webb', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '17-Jul-2009'},
  {:title => '8 Mile', :director => 'Curtis Hanson', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '8-Nov-2002'},
  {:title => 'A Beautiful Mind', :director => 'Ron Howard', :rating => 'PG-13', :location => 'F', :quality => '480p', :release_date => '21-Dec-2001'},
  {:title => 'Air Force One', :director => 'Wolfgang Petersen', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '25-Jul-1997'},
  {:title => 'Airplane!', :director => 'Jim Abrahams, David & Jerry Zucker', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '27-Jun-1980'},
  {:title => 'Alice in Wonderland', :director => 'Tim Burton', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '5-Mar-2010'},
  {:title => 'Angels and Demons', :director => 'Ron Howard', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '15-May-2009'},
  {:title => 'Batman Begins', :director => 'Christopher Nolan', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '15-Jun-2005'},
  {:title => 'Batman: Gotham Knight', :director => 'Toshi Hiruma, Bruce Timm', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '8-Jul-2008'},
  {:title => 'Batman: The Dark Knight', :director => 'Christopher Nolan', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '18-Jul-2008'},
  {:title => 'Batman: The Dark Knight', :director => 'Christopher Nolan', :rating => 'PG-13', :location => 'K', :quality => '1080p', :release_date => '18-Jul-2008'},
  {:title => 'Battle: Los Angeles', :director => 'Jonathan Liebesman', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '11-Mar-2011'},
  {:title => 'Black Hawk Down', :director => 'Ridley Scott', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '28-Dec-2001'},
  {:title => 'Bolt', :director => 'Dan Fogelman', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '21-Nov-2008'},
  {:title => 'Bond: Casino Royale', :director => 'Martin Campbell', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '17-Nov-2006'},
  {:title => 'Bond: Die Another Day', :director => 'Lee Tamahori', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '22-Nov-2002'},
  {:title => 'Bond: Dr. No', :director => 'Terence Young', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '8-May-1963'},
  {:title => 'Bond: For Your Eyes Only', :director => 'John Glen', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '26-Jun-1981'},
  {:title => 'Bond: From Russia with Love', :director => 'Terence Young', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '8-Apr-1964'},
  {:title => 'Bond: Goldeneye', :director => 'Martin Campbell', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '17-Nov-1995'},
  {:title => 'Bond: Goldfinger', :director => 'Guy Hamilton', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '22-Dec-1964'},
  {:title => 'Bond: License to Kill', :director => 'John Glen', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '14-Jul-1989'},
  {:title => 'Bond: Live and Let Die', :director => 'Guy Hamilton', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '27-Jun-1973'},
  {:title => 'Bond: Moonraker', :director => 'Lewis Gilbert', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '29-Jun-1979'},
  {:title => 'Bond: Quantum of Solace', :director => 'Marc Forster', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '14-Nov-2008'},
  {:title => 'Bond: The Man with the Golden Gun', :director => 'Guy Hamilton', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '18-Dec-1974'},
  {:title => 'Bond: The World is Not Enough', :director => 'Michael Apted', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '19-Nov-1999'},
  {:title => 'Bond: Thunderball', :director => 'Terence Young', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '21-Dec-1965'},
  {:title => 'Bond: Tomorrow Never Dies', :director => 'Roger Spottiswoode', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '19-Dec-1997'},
  {:title => 'Borat', :director => 'Larry Charles', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '3-Nov-2006'},
  {:title => 'Bridesmaids', :director => 'Paul Feig', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '13-May-2011'},
  {:title => 'Captain America: The First Avenger', :director => 'Joe Johnston', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '22-Jul-2011'},
  {:title => 'Cloverfield', :director => 'Matt Reeves', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '18-Jan-2008'},
  {:title => 'Couples Retreat', :director => 'Peter Billingsley', :rating => 'PG-13', :location => 'E', :quality => '480p', :release_date => '9-Oct-2009'},
  {:title => 'Crazy Stupid Love', :director => 'Glenn Ficarra, John Requa', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '29-Jul-2011'},
  {:title => 'Despicable Me', :director => 'Pierre Coffin, Chris Renaud', :rating => 'PG', :location => 'F', :quality => '1080p', :release_date => '9-Jul-2010'},
  {:title => 'District 9', :director => 'Neill Blomkamp', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '14-Aug-2009'},
  {:title => 'Dodgeball: A True Underdog Story', :director => 'Rawson Marshall THurber', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '18-Jun-2004'},
  {:title => 'Drive', :director => 'Nicholas Winding Refn', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '16-Sep-2011'},
  {:title => 'Drunken Master', :director => 'Yuen Woo-ping', :rating => 'R', :location => 'F', :quality => '480p', :release_date => '20-Oct-2000'},
  {:title => 'Easy A', :director => 'Will Gluck', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '17-Sep-2010'},
  {:title => 'Equilibrium', :director => 'Kurt Wimmer', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '6-Dec-2002'},
  {:title => 'Eternal Sunshine of the Spotless Mind', :director => 'Michael Gondry', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '19-Mar-2004'},
  {:title => 'Fantastic Mr. Fox', :director => 'Wes Anderson', :rating => 'PG', :location => 'E', :quality => '480p', :release_date => '13-Nov-2009'},
  {:title => 'Fight Club', :director => 'David Fincher', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '15-Oct-1999'},
  {:title => 'Finding Nemo', :director => 'Andrew Stanton', :rating => 'G', :location => 'K', :quality => '720p', :release_date => '30-May-2003'},
  {:title => 'Food Inc', :director => 'Robert Kenner', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '12-Jun-2009'},
  {:title => 'Forbidden Kingdom', :director => 'Rob Minkoff', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '18-Apr-2008'},
  {:title => 'G.I. Joe Rise of Cobra', :director => 'Stephen Sommers', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '7-Aug-2009'},
  {:title => 'Gladiator', :director => 'Ridley Scott', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '5-May-2000'},
  {:title => 'Good Night and Good Luck', :director => 'George Clooney', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '7-Oct-2005'},
  {:title => 'Harry Potter and the Chamber of Secrets', :director => 'Chris Columbus', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '15-Nov-2002'},
  {:title => 'Harry Potter and the Deathly Hallows Part I', :director => 'David Yates', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '19-Nov-2010'},
  {:title => 'Harry Potter and the Deathly Hallows Part II', :director => 'David Yates', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '15-Jul-2011'},
  {:title => 'Harry Potter and the Goblet of Fire', :director => 'Mike Newell', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '18-Nov-2005'},
  {:title => 'Harry Potter and the Half Blood Prince', :director => 'David Yates', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '15-Jul-2009'},
  {:title => 'Harry Potter and the Order of the Phoenix', :director => 'David Yates', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '11-Jul-2007'},
  {:title => 'Harry Potter and the Prisoner of Azkaban', :director => 'Alfonso Cuaron', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '4-Jun-2004'},
  {:title => "Harry Potter and the Sorcerer's Stone", :director => 'Chris Columbus', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '16-Nov-2001'},
  {:title => 'Hero', :director => 'Zhang Yimou', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '27-Aug-2004'},
  {:title => 'How to Train Your Dragon', :director => 'Dean DeBlois, Chris Sanders', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '26-Mar-2010'},
  {:title => 'Hustle and Flow', :director => 'Craig Brewer', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '22-Jul-2005'},
  {:title => 'I am Legend', :director => 'Francis Lawrence', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '14-Dec-2007'},
  {:title => 'Inception', :director => 'Christopher Nolan', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '16-Jul-2010'},
  {:title => 'Inception', :director => 'Christopher Nolan', :rating => 'PG-13', :location => 'K', :quality => '1080p', :release_date => '16-Jul-2010'},
  {:title => 'Indiana Jones: Raiders of the Lost Ark', :director => 'George Lucas', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '12-Jun-1981'},
  {:title => 'Indiana Jones: Temple of Doom', :director => 'George Lucas', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '23-May-1984'},
  {:title => 'Indiana Jones: The Last Crusade', :director => 'George Lucas', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '24-May-1989'},
  {:title => 'Inglourious Basterds', :director => 'Quentin Tarantino', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '21-Aug-2009'},
  {:title => 'Ip Man', :director => 'Wilson Yip', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '28-Jan-2011'},
  {:title => 'Iron Man', :director => 'Jon Favreau', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '2-May-2008'},
  {:title => 'Iron Man 2', :director => 'Jon Favreau', :rating => 'PG-13', :location => 'F', :quality => '1080p', :release_date => '7-May-2010'},
  {:title => 'Julie and Julia', :director => 'Nora Ephron', :rating => 'PG-13', :location => 'K', :quality => '480p', :release_date => '7-Aug-2009'},
  {:title => 'Kill Bill Vol. 1', :director => 'Quentin Tarantino', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '10-Oct-2003'},
  {:title => 'Kill Bill Vol. 2', :director => 'Quentin Tarantino', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '16-Apr-2004'},
  {:title => 'Kingdom of Heaven', :director => 'Ridley Scott', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '6-May-2005'},
  {:title => 'Kiss Kiss Bang Bang', :director => 'Shane Black', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '21-Oct-2005'},
  {:title => 'Kung Fu Hustle', :director => 'Stephen Chow', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '8-Apr-2005'},
  {:title => 'Law Abiding Citizen', :director => 'F. Gary Gray', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '16-Oct-2009'},
  {:title => "Legends of the Guardians: Owls of Ga'Hoole", :director => 'Zack Snyder', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '24-Sep-2010'},
  {:title => 'Marley and Me', :director => 'David Frankel', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '25-Dec-2008'},
  {:title => 'Mean Girls', :director => 'Mark Waters', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '30-Apr-2004'},
  {:title => 'Memento', :director => 'Christopher Nolan', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '16-Mar-2001'},
  {:title => 'Michael Clayton', :director => 'Tony Gilroy', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '5-Oct-2007'},
  {:title => 'Mission Impossible I', :director => 'Brian De Palma', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '5-May-1996'},
  {:title => 'Mission Impossible II', :director => 'John Woo', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '24-May-2000'},
  {:title => 'Mission Impossible III', :director => 'J.J. Abrams', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '5-May-2006'},
  {:title => "Nick and Norah's Infinite Playlist", :director => 'Peter Sollett', :rating => 'PG-13', :location => 'F', :quality => '1080p', :release_date => '3-Oct-2008'},
  {:title => "Ocean's Eleven", :director => 'Steven Soderbergh', :rating => 'PG-13', :location => 'K', :quality => '1080p', :release_date => '7-Dec-2001'},
  {:title => "Ocean's Eleven", :director => 'Steven Soderbergh', :rating => 'PG-13', :location => 'K', :quality => '480p', :release_date => '7-Dec-2001'},
  {:title => "Ocean's Eleven", :director => 'Steven Soderbergh', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '7-Dec-2001'},
  {:title => "Ocean's Thirteen", :director => 'Steven Soderbergh', :rating => 'PG-13', :location => 'K', :quality => '1080p', :release_date => '8-Jun-2007'},
  {:title => "Ocean's Thirteen", :director => 'Steven Soderbergh', :rating => 'PG-13', :location => 'K', :quality => '480p', :release_date => '8-Jun-2007'},
  {:title => "Ocean's Thirteen", :director => 'Steven Soderbergh', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '8-Jun-2007'},
  {:title => "Ocean's Twelve", :director => 'Steven Soderbergh', :rating => 'PG-13', :location => 'K', :quality => '1080p', :release_date => '10-Dec-2004'},
  {:title => "Ocean's Twelve", :director => 'Steven Soderbergh', :rating => 'PG-13', :location => 'K', :quality => '480p', :release_date => '10-Dec-2004'},
  {:title => "Ocean's Twelve", :director => 'Steven Soderbergh', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '10-Dec-2004'},
  {:title => "Pirates of the Caribbean: At World's End", :director => 'Gore Verbinski', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '25-May-2007'},
  {:title => "Pirates of the Caribbean: Curse of the Black Pearl", :director => 'Gore Verbinski', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '9-Jul-2003'},
  {:title => "Pirates of the Caribbean: Dead Man's Chest", :director => 'Gore Verbinski', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '7-Jul-2006'},
  {:title => 'Pirates of the Caribbean: On Stranger Tides', :director => 'Rob Marshall', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '20-May-2011'},
  {:title => 'Pulp Fiction', :director => 'Quentin Tarantino', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '14-Oct-1994'},
  {:title => 'Ratatouille', :director => 'Brad Bird', :rating => 'G', :location => 'K', :quality => '720p', :release_date => '29-Jun-2007'},
  {:title => 'Real Steel', :director => 'Shawn Levy', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '7-Oct-2011'},
  {:title => 'Rounders', :director => 'John Dahl', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '11-Sep-1998'},
  {:title => 'Rush Hour', :director => 'Brett Ratner', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '18-Sep-1998'},
  {:title => 'Rush Hour 2', :director => 'Brett Ratner', :rating => 'PG-13', :location => 'K', :quality => '480p', :release_date => '3-Aug-2001'},
  {:title => 'Rush Hour 3', :director => 'Brett Ratner', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '10-Aug-2007'},
  {:title => 'Saving Private Ryan', :director => 'Steven Spielberg', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '24-Jul-1998'},
  {:title => 'Scott Pilgrim VS the World', :director => 'Edgar Wright', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '13-Aug-2010'},
  {:title => 'Shaolin Soccer', :director => 'Stephen Chow', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '2-Apr-2004'},
  {:title => 'Shawshank Redemption', :director => 'Frank Darabont', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '23-Sep-1994'},
  {:title => 'Sherlock Holmes', :director => 'Guy Ritchie', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '25-Dec-2009'},
  {:title => 'Sin City', :director => 'Frank Miller, Robert Rodriguez, Quentin Tarantino', :rating => 'R', :location => 'K', :quality => '1080p', :release_date => '1-Apr-2005'},
  {:title => 'Slumdog Millionaire', :director => 'Danny Boyle', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '12-Nov-2008'},
  {:title => 'Space Jam', :director => 'Joe Pytka', :rating => 'PG', :location => 'F', :quality => '480p', :release_date => '15-Nov-1996'},
  {:title => 'Speed Racer', :director => 'Andy & Larry Wachowski', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '9-May-2008'},
  {:title => 'Star Trek', :director => 'J.J. Abrams', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '8-May-2009'},
  {:title => 'Star Wars Episode 2: Attack of the Clones', :director => 'George Lucas', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '16-May-2002'},
  {:title => 'Star Wars Episode 3: Revenge of the Sith', :director => 'George Lucas', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '19-May-2005'},
  {:title => 'Star Wars Episode 4: A New Hope', :director => 'George Lucas', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '25-May-1977'},
  {:title => 'Star Wars Episode 5: The Empire Strikes Back', :director => 'Irvin Kershner', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '21-May-1980'},
  {:title => 'Star Wars Episode 6: Return of the Jedi', :director => 'Richard Marquand', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '25-May-1983'},
  {:title => 'Sucker Punch', :director => 'Zack Snyder', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '25-Mar-2011'},
  {:title => 'Superbad', :director => 'Greg Mottola', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '17-Aug-2007'},
  {:title => 'Taken', :director => 'Pierre Morel', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '30-Jan-2009'},
  {:title => 'Talladega Nights', :director => 'Adam McKay', :rating => 'PG-13', :location => 'F', :quality => '1080p', :release_date => '4-Aug-2006'},
  {:title => 'The A-Team', :director => 'Joe Carnahan', :rating => 'PG-13', :location => 'F', :quality => '1080p', :release_date => '11-Jun-2010'},
  {:title => 'The American', :director => 'Anton Corbijn', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '1-Sep-2010'},
  {:title => 'The Bourne Identity', :director => 'Doug Liman', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '14-Jun-2002'},
  {:title => 'The Bourne Supremacy', :director => 'Paul Greengrass', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '23-Jul-2004'},
  {:title => 'The Bourne Ultimatum', :director => 'Paul Greengrass', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '3-Aug-2007'},
  {:title => 'The Da Vinci Code', :director => 'Ron Howard', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '19-May-2006'},
  {:title => 'The Departed', :director => 'Martin Scorsese', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '6-Oct-2006'},
  {:title => 'The Diving Bell and the Butterfly', :director => 'Julian Schnabel', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '30-Nov-2007'},
  {:title => 'The Expendables', :director => 'Sylvester Stallone', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '13-Aug-2010'},
  {:title => 'The Fast and the Furious', :director => 'Rob Cohen', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '22-Jun-2001'},
  {:title => 'The Fast and the Furious: Fast and Furious', :director => 'Justin Lin', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '3-Apr-2009'},
  {:title => 'The Fast and the Furious: Fast Five', :director => 'Justin Lin', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '29-Apr-2011'},
  {:title => 'The Fast and the Furious: Tokyo Drift', :director => 'Justin Lin', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '16-Jun-2006'},
  {:title => 'The Fast and the Furious: Too Fast Too Furious', :director => 'John Singleton', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '6-Jun-2003'},
  {:title => 'The Golden Compass', :director => 'Chris Weitz', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '7-Dec-2007'},
  {:title => 'The Good, the Bad, and the Ugly', :director => 'Sergio Leone', :rating => 'M', :location => 'K', :quality => '480p', :release_date => '29-Dec-1967'},
  {:title => 'The Hangover', :director => 'Todd Phillips', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '26-May-2011'},
  {:title => "The Hitchhiker's Guide to the Galaxy", :director => 'Garth Jennings', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '29-Apr-2005'},
  {:title => 'The Hurt Locker', :director => 'Kathryn Bigelow', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '26-Jun-2009'},
  {:title => 'The Incredibles', :director => 'Brad Bird', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '5-Nov-2004'},
  {:title => 'The Italian Job', :director => 'F. Gary Gray', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '30-May-2003'},
  {:title => 'The Karate Kid', :director => 'Harald Zwart', :rating => 'PG', :location => 'F', :quality => '720p', :release_date => '11-Jun-2010'},
  {:title => "The King's Speech", :director => 'Tom Hooper', :rating => 'R', :location => 'F', :quality => '720p', :release_date => '26-Nov-2010'},
  {:title => 'The Lion King', :director => 'Roger Allers, Rob Minkoff', :rating => 'G', :location => 'K', :quality => '720p', :release_date => '15-Jun-1994'},
  {:title => 'The Lord of the Rings: Fellowship of the Ring', :director => 'Peter Jackson', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '19-Dec-2001'},
  {:title => 'The Lord of the Rings: Return of the King', :director => 'Peter Jackson', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '17-Dec-2003'},
  {:title => 'The Lord of the Rings: The Two Towers', :director => 'Peter Jackson', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '18-Dec-2002'},
  {:title => 'The Matrix', :director => 'Andy & Larry Wachowski', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '31-Mar-1999'},
  {:title => 'The Mummy', :director => 'Stephen Sommers', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '7-May-1999'},
  {:title => 'The Mummy Returns', :director => 'Stephen Sommers', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '4-May-2001'},
  {:title => 'The Mummy: Tomb of the Dragon Emperor', :director => 'Rob Cohen', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '1-Aug-2008'},
  {:title => 'The Prestige', :director => 'Christopher Nolan', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '20-Oct-2006'},
  {:title => 'The Simpsons Movie', :director => 'David Silverman', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '27-Jul-2007'},
  {:title => 'The Social Network', :director => 'David Fincher', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '1-Oct-2010'},
  {:title => 'The Terminal', :director => 'Steven Spielberg', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '18-Jun-2004'},
  {:title => 'The Terminator', :director => 'James Cameron', :rating => 'R', :location => 'K', :quality => '480p', :release_date => '26-Oct-1984'},
  {:title => 'The Terminator: Judgement Day', :director => 'James Cameron', :rating => 'R', :location => 'K', :quality => '480p', :release_date => '3-Jul-1991'},
  {:title => 'The Terminator: Rise of the Machines', :director => 'Jonathan Mostow', :rating => 'R', :location => 'K', :quality => '480p', :release_date => '2-Jul-2003'},
  {:title => 'The Terminator: Salvation', :director => 'McG', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '21-May-2009'},
  {:title => 'Thor', :director => 'Kenneth Branagh', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '6-May-2011'},
  {:title => 'Toy Story 3', :director => 'Lee Unkrich', :rating => 'G', :location => 'F', :quality => '720p', :release_date => '18-Jun-2010'},
  {:title => 'Transformers', :director => 'Michael Bay', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '3-Jul-2007'},
  {:title => 'Transformers', :director => 'Michael Bay', :rating => 'PG-13', :location => 'K', :quality => '1080p', :release_date => '3-Jul-2007'},
  {:title => 'Transformers: Dark of the Moon', :director => 'Michael Bay', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '29-Jun-2011'},
  {:title => 'Transformers: Revenge of the Fallen', :director => 'Michael Bay', :rating => 'PG-13', :location => 'K', :quality => '720p', :release_date => '24-Jun-2009'},
  {:title => 'Tron: Legacy', :director => 'Joseph Kosinski', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '17-Dec-2010'},
  {:title => 'Up', :director => 'Pete Docter, Bob Peterson', :rating => 'PG', :location => 'K', :quality => '720p', :release_date => '29-May-2009'},
  {:title => 'V for Vendetta', :director => 'James McTeigue', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '17-Mar-2006'},
  {:title => 'Wall-E', :director => 'Andrew Stanton', :rating => 'G', :location => 'F', :quality => '720p', :release_date => '27-Jun-2008'},
  {:title => 'Wall-E', :director => 'Andrew Stanton', :rating => 'G', :location => 'K', :quality => '1080p', :release_date => '27-Jun-2008'},
  {:title => 'Wallace and Gromit: Curse of the Were-Rabbit', :director => 'Nick Park, Steve Box', :rating => 'G', :location => 'K', :quality => '1080p', :release_date => '5-Oct-2005'},
  {:title => 'Wanted', :director => 'Timur Bekmambetov', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '27-Jun-2008'},
  {:title => 'Watchmen', :director => 'Zack Snyder', :rating => 'R', :location => 'K', :quality => '720p', :release_date => '6-Mar-2009'},
  {:title => 'X-Men First Class', :director => 'Matthew Vaughn', :rating => 'PG-13', :location => 'F', :quality => '720p', :release_date => '3-Jun-2011'}
]

POTATOES.each do |movie|
  Movie.create!(movie)
end